name: razer-ctl-ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y libudev-dev libxdo-dev librust-atk-dev libgtk-3-dev gcc-mingw-w64

      - name: Install target for Windows
        run: rustup target add x86_64-pc-windows-gnu
      - name: Run clippy
        run: cargo clippy --all-targets --all-features
      - name: Build for Windows
        run: cargo build --verbose --release --target x86_64-pc-windows-gnu
      - name: Build for Linux
        run: cargo build --verbose --release
